# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Clean的收藏
email: clean_li@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  庄周梦胡蝶，胡蝶为庄周。
  一体更变易，万事良悠悠。
  乃知蓬莱水，复作清浅流。
  青门种瓜人，旧日东陵侯。
  富贵固如此，营营何所求。
baseurl: /clean_collecting # the subpath of your site, e.g. /blog
author: Clean Li
google_analytics: true
